# Generated by Django 4.2.4 on 2023-08-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="choice",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="vote.choice"
            ),
            preserve_default=False,
        ),
    ]
