# Generated by Django 4.2.4 on 2023-08-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
