# Generated by Django 4.2.4 on 2023-08-17 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_like",
            field=models.ManyToManyField(
                blank=True, related_name="comment_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
