# Generated by Django 4.2.3 on 2023-08-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonuservote',
            name='MBTI',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nonuservote',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('W', '여성')], max_length=1, null=True, verbose_name='성별'),
        ),
    ]
