# Generated by Django 4.2.4 on 2023-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonuservote",
            name="gender",
            field=models.CharField(
                choices=[("M", "M"), ("W", "W")],
                max_length=1,
                null=True,
                verbose_name="성별",
            ),
        ),
    ]
