# Generated by Django 4.2.4 on 2023-08-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="uservote", name="poll",),
    ]
