# Generated by Django 4.2.4 on 2023-08-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_comment_poll_id_alter_comment_user_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="poll_id", new_name="poll",
        ),
    ]
