# Generated by Django 4.2.3 on 2023-08-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_uservote_alter_poll_owner_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.tempuser'),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.tempuser'),
        ),
    ]
