# Generated by Django 4.2.4 on 2023-08-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_comment_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="choice",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="vote.choice"
            ),
        ),
    ]
