# Generated by Django 4.2.4 on 2023-08-08 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0003_rename_poll_id_comment_poll"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="choice",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="vote.choice"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vote.poll"
            ),
        ),
    ]
