# Generated by Django 4.2.3 on 2023-08-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_tempuser_alter_poll_owner_alter_uservote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='gender',
            field=models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)')], default=2, max_length=1, verbose_name='성별'),
            preserve_default=False,
        ),
    ]
