# Generated by Django 4.2.4 on 2023-08-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0003_comment_choice"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="choice",),
    ]
