# Generated by Django 4.2.3 on 2023-08-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_tempuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonuservote',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('W', '여성')], max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('W', '여성')], max_length=1, verbose_name='성별'),
        ),
    ]
