# Generated by Django 4.2.4 on 2023-08-08 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0004_comment_choice_alter_comment_poll"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="choice",),
    ]
