# Generated by Django 4.2.4 on 2023-08-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0005_remove_comment_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonuservote",
            name="poll",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="vote.poll"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nonuservote", name="MBTI", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="nonuservote",
            name="gender",
            field=models.CharField(
                choices=[("M", "남성"), ("W", "여성")],
                max_length=1,
                null=True,
                verbose_name="성별",
            ),
        ),
    ]
