# Generated by Django 4.2.4 on 2023-08-11 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vote", "0006_remove_comment_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
