# Generated by Django 4.2.4 on 2023-08-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="poll", name="owner",),
        migrations.RemoveField(model_name="vote", name="choice",),
        migrations.RemoveField(model_name="vote", name="poll",),
        migrations.RemoveField(model_name="vote", name="user",),
        migrations.DeleteModel(name="Choice",),
        migrations.DeleteModel(name="Poll",),
        migrations.DeleteModel(name="Vote",),
    ]
