# Generated by Django 4.2.3 on 2023-08-04 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userk_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userk',
        ),
    ]
