# Generated by Django 4.2.4 on 2023-08-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonUser',
        ),
    ]
