# Generated by Django 4.2.3 on 2023-08-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_mbti'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakaoId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
